config/routes.rb
FamoustmRails::Application.routes.draw do |map|
  

  resources :services do
    resources :posts
  end

  
  root :to => "home#index"
  
  devise_for :users
  resources :users

  match 'trademarks/last_updated'  => 'trademarks#last_updated', :as => :trademarks_last_updated
  match '/search'  => 'trademarks#search',:as => :search_trademark
  resources :trademarks,:policies
  
  match 'categories/all' => 'categories#all_categories',:as  => :all_categories
  resources :categories do
    resources :trademarks
  end
  
  match 'about'  => "home#about" , :as  => :about
  match 'contact' => "home#contact", :as  => :contact
  

end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :posts
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # GET /services
  # GET /services.xml
  def index
    @services = Service.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @services }
    end
  end

  # GET /services/1
  # GET /services/1.xml
  def show
    @service = Service.find(params[:id])
    @services = Service.all
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @service }
    end
  end

  # GET /services/new
  # GET /services/new.xml
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.xml
  def create
    @service = Service.new(params[:service])

    respond_to do |format|
      if @service.save
        format.html { redirect_to(@service, :notice => 'Service was successfully created.') }
        format.xml  { render :xml => @service, :status => :created, :location => @service }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.xml
  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to(@service, :notice => 'Service was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.xml
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to(services_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :intro %><br />
    <%= f.text_area :intro %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/_services_header.html.erb
<% title t('service.services') %>

<% content_for :submenu do %>
	<ul class="submenu">
	<% if !@services.blank? %>
		<% for s in @services %>
			<li>
				<%= link_to s.name, service_path(s),:class => "cat" %>
			</li>
		<% end %>
	<% end %>
	<li>
		<%= link_to t('service.new'), new_service_path ,:class => "cat"%>
	</li>
	
	</ul>
<% end %>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<%= render :partial => 'services_header' %>

app/views/services/new.html.erb
<%= title t('service.new') %>



<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<%= render :partial => 'services_header' %>


<p id="notice"><%= notice %></p>

<div id="service_name"><%= @service.name %></div>
<div id="service_subtitle">
	<%= @service.intro %>
</div>

<div id="service_description">
	<%= simple_format @service.description %>
	
	<%= link_to 'Edit', edit_service_path(@service) %> |
	<%= link_to 'Back', services_path %>
</div>