config/routes.rb
FamoustmRails::Application.routes.draw do |map|
  

  resources :services do
    resources :posts
  end

  
  root :to => "home#index"
  
  devise_for :users
  resources :users

  match 'trademarks/last_updated'  => 'trademarks#last_updated', :as => :trademarks_last_updated
  match '/search'  => 'trademarks#search',:as => :search_trademark
  resources :trademarks,:policies
  
  match 'categories/all' => 'categories#all_categories',:as  => :all_categories
  resources :categories do
    resources :trademarks
  end
  
  match 'about'  => "home#about" , :as  => :about
  match 'contact' => "home#contact", :as  => :contact
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :trademarks
  
  def self.all_categories
    @categories = Category.order("id").includes(:trademarks)
  end
  
  def self.find_category(id)
    Category.find(id)
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :service
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :posts
end

app/models/trademark.rb
class Trademark < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>",:tiny => "50x50#" }
  belongs_to :category
  
  def self.all_trademarks
    @trademarks = Trademark.order("id")
    
  end
  
  def self.find_tradmark(id)
    @trademarks = Trademark.find(id)
  end
  
  def self.check_duplicated(reg_number)
    @trademarks = Trademark.find_by_reg_number(reg_number)
    return true if @trademarks.nil?
    return false
  end
  
  def self.get_lastest(number)
    @trademarks = Trademark.order("id DESC").limit(number)
  end
  
  def self.search(q)
    @trademarks = Trademark.where(["name like ? ","%#{q}%"])
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :authenticatable,  :recoverable, :rememberable, :trackable, :validatable, :registerable #,:confirmable
  attr_accessible :email, :password, :password_confirmation
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  window_title "Welcome"
  
  def index
    render :layout  => "home"
  end
  
  def about
    render :layout  => "application"
  end
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  
  window_title 'Policy'
  def index
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
   window_title "Search"
  def index
   
  end

  def search
    
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # GET /services
  # GET /services.xml
  def index
    @services = Service.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @services }
    end
  end

  # GET /services/1
  # GET /services/1.xml
  def show
    @service = Service.find(params[:id])
    @services = Service.all
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @service }
    end
  end

  # GET /services/new
  # GET /services/new.xml
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.xml
  def create
    @service = Service.new(params[:service])

    respond_to do |format|
      if @service.save
        format.html { redirect_to(@service, :notice => 'Service was successfully created.') }
        format.xml  { render :xml => @service, :status => :created, :location => @service }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.xml
  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to(@service, :notice => 'Service was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.xml
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to(services_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    
  end
  
  def new
    
  end
  
  def show
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/trademarks_helper.rb
module TrademarksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/contact.html.erb
<!--contact us-->

<% content_for :page_title do %>
    <%= t('about.contact_us') %>
<% end %>

app/views/about/us.html.erb
<!--about us-->

<% content_for :page_title do %>
    About Us
<% end %>

app/views/layouts/_html_header.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<title><%= window_title %></title>
	<%= stylesheet_link_tag :all, :cache => true %>
	<%= javascript_include_tag :defaults, :cache => true %>
	<%= csrf_meta_tag %> 
</head>

app/views/layouts/application.html.erb
<%= render :partial => "layouts/html_header" %>

<body>
<!--page outline-->
	<div id="page_outline">
		<a name="top"></a>
		<!--page header: logo, topmenu,main navigator-->
		<%= render :partial => 'shared/site_navigator' %>

		
			<!-- customize the page content from here -->
		
		<% if flash[:notice] %>
		<div class="notice">
			<%= flash[:notice] %>
		</div>
		<% end %>
		
		<% if flash[:alert] %>
		<div class="alert">
			<%= flash[:alert] %>
		</div>
		<% end %>
		
		<div id="page_content">
			<!--main content-->
			<div class="basic_page_header">
				<span><%= page_title %></span>
				<div class="header_right">
					<%#= yield :header_right %>
					<a href="javascript:;" onClick="Effect.BlindDown('call_us_panel',{duration:0.3});" class="call_us"><%= t('menu.call_us') %></a>
					
				</div>
				<div style="min-height:35px;padding-bottom:5px;">
					<%= yield :submenu %>
				</div>
				
				<div id="call_us_panel" style="display:none;">
					<div id="ask_us_form">
					<!#TODO--please change the following content as a form-->
						<h1>
							<%= t('menu.ask_us') %>
						</h1>
					
						<%= t('contact.name') %>: <br/><input type="text" size="12"></input><p/>
						<%= t('contact.email') %>: <br/><input type="text" size="12"></input><p/>
						<%= t('contact.comment') %>:<br/><textarea name="comment" rows="8" cols="40"></textarea>
						<p/>
						<button name="submit">OK</button>
					</div>
					<div id="call_us_now">
						<h1>
							或<%= t('menu.call_us') %><p/>
							4008-123-123
						<h1>
						<div id="our_address" >
							上海：南京东路100号1座14楼A<br/>
							北京 南门二甲胡同345号C座908室<br/>
							纽约 5th Ave. C7-0987<br/>
							安特卫普 Green Ave. 770C<br/>
						</div>
					</div>
					<div style="clear:both;">
						
					</div>
				</div>
			</div>
			<div class="basic_page_content">
				<%= yield %>
				<div id="clear" style = "clear:both;"></div>
			</div>
			
		</div>
		<!--foot-->
		<div class="page_foot">
			<a href="contact.html">联系我们</a> | 
			<a href="ip_policy.html">法律声明</a> |
			上海市××律师事务所 主办  ICP备07012690号 | &copy;2010 版权所有 | 在线服务：MSN QQ
		</div>
		
	</div>
</body>
</html>

app/views/layouts/home.html.erb
<%= render :partial => "layouts/html_header" %>

<body>
<!--page outline-->
	<div id="page_outline">
		<!--page header: logo, topmenu,main navigator-->
			<%= render :partial => 'shared/site_navigator' %>
			
			
		<!-- customize the page content from here -->
		<!--page cover: cover story-->
		<div id="page_cover" >
			<a class="subtitle" href="/categories">或者直接按照全部分类浏览。只需点击这里开始。</a>
			
				<!--<a id="know_us" href="confirm/faq.html">
					什么是驰名商标
				</a>
				
				<a id="trust_us" href="dispute/index.html">
					我被侵权了
				</a>
				
				<a id="call_us" href="contact.html">
					<span>马上联系我们</span><br/>
					<span id="call">4008-123-456</span>
				</a>-->
			
		</div>
		
		<!--Something about firm: 3 main business-->
		<div id="main_biz">
			<div id="tm_confirm" class="biz">
				<a href="confirm/index.html" class="title">驰名商标认定</a>
				我们帮助您轻松搞定全部驰名商标认定环节，快速打开全球市场通道。
				
				<ul>
					<li>
						<a href="confirm/faq.html">什么是驰名商标</a>
					</li>
					<li>
						<a href="confirm/process.html">了解认定全过程</a>
					</li>
					
				</ul>
			</div>
			<div id="tm_supervisor" class="biz">
				<a href="supervisor/index.html" class="title">驰名商标监控</a>
				帮助您监控全球商业市场驰名商标侵权行为，及时提出注册异议，保护您的驰名商标在全球的经济利益。
				
				<ul>
					<li>
						<a href="supervisor/global.html">监控覆盖范围</a>
					</li>
					<li>
						<a href="supervisor/partener.html">我们的合作伙伴</a>
					</li>
				</ul>
				
			</div>
			<div id="tm_dispute" class="biz">
				<a href="dispute/index.html" class="title">商标权争议</a>
				对有争议的驰名商标案件，协助客户保护自己的权益，抵制不法侵害。
				
				<ul>
					<li>
						<a href="dispute/cases.html">商标争议案例精选</a>
					</li>
					<li>
						<a href="dispute/proecss.html">商标权争端解决流程</a>
					</li>
				</ul>
				
			</div>
			
			<!-- clients top 10-->
			<div id="clients_list">
				<ul>
					<li>
						<a href="http://www.nike.com">
							<img src="images/clients/nike.png" />
						</a>
					</li>
					<li>
						<a href="http://www.marriott.com">
							<img src="images/clients/marriott.png" />
						</a>
					</li>
					<li>
						<a href="http://www.nokia.com">
							<img src="images/clients/nsn.png" />
						</a>
					</li>
					<li>
						<a href="http://www.oracle.com">
							<img src="images/clients/oracle.png" />
						</a>
					</li>
					<li>
						<a href="http://www.pbs.com">
							<img src="images/clients/pbs.png" />
						</a>
					</li>
					<li>
						<a href="http://www.sandisk.com">
							<img src="images/clients/sandisk.png" />
						</a>
					</li>
					<li>
						<a href="http://www.tmobile.com">
							<img src="images/clients/tmobile.png" />
						</a>
					</li>
					<li>
						<a href="http://www.virgin.com">
							<img src="images/clients/virgin.png" />
						</a>
					</li>
					<!--<li>
						<a href="http://www.symantec.com">
							<img src="images/clients/symantec.png" />
						</a>
					</li>-->
				</ul>
			</div>
		</div>
		
		
		<!--something else: firm's news, some useful links & faq or clients feedback-->
		<!--<div id="site_news">
			<div id="site_news_list">
			<a class="title" href="news/index.html">驰名商标动态</a>
			<ul>
				<li>
					<a href="news/1.html">小天鹅勇夺最佳自主创新设计奖</a>
				</li>
				<li>
					<a href="news/2.html">海宝背后的产权保卫战</a>
				</li>
				<li>
					<a href="news/3.html">两会代表委员聚焦知识产权保护</a>
				</li>
			</ul>
			</div>
		</div>-->
		
		<!--end of customized content-->
		<div class="page_foot">
			<a href="contact.html">联系我们</a> | 
			<a href="ip_policy.html">法律声明</a> |
			上海市××律师事务所 主办  ICP备07012690号 | &copy;2010 版权所有 | 在线服务：MSN QQ
		</div>
	</div>
</body>
</html>

app/views/shared/_categories.html.erb
	<ul class="submenu">
		<% if !@categories.blank? %>
		   
			<li>
				<%= link_to t("category.all"),all_categories_path,:remote => true,:class => "cat"  %>
					<%# if @categories.count > 0 %>
					<!--<span class="number"><%#= @categories.count %></span>-->
					<%# end %>
			
		    </li>
			<li>
				<%= link_to t("category.lastest"), trademarks_last_updated_path,{:class => "cat"},:remote => true %>
			</li>
			<li>
				<% unless @category.nil? %>
					
					<%= link_to t('tm.add'), new_category_trademark_path(@category),:class => "cat" %>
					
				<% end %>
			</li>
			<li>
				<%# if user_signed_in? %>
					<%= link_to t('category.add'),new_category_path,:class => 'cat' %>
				<%# end %>
			</li>
		<% else %>
		  
		<% end %>
		
	</ul>
	

app/views/shared/_category_list.html.erb
<!-- show all categories-->
	<div id="all_categories" >
		
		<% if @categories.count > 0 %>
		<ul>
		  <% for cate in @categories %>
		    <li>
		 		 <a href="<%= category_path(cate) %>" class="cat_list">
				 	<%= cate.name %>
						<% if cate.trademarks.count > 0 %>
						<span class="number"><%= cate.trademarks.count %></span>
						<% end %>
				 </a>
		    </li>
		  <% end %>
		</ul>
	    <% end %>
	</div>

app/views/shared/_site_navigator.html.erb
<div id="page_header">
			<!-- logo -->
			<div id="site_logo">
				<a href="/"></a>
			</div>
			<!-- main navigator -->
			<div id="site_navigator">
				<ul>
					<li>
						<a href="/" class="menu_item"><%= t('menu.home') %></a>
					</li>
					<li>
						<%= link_to t('menu.browse'),categories_path,{:class => "menu_item"} %>
					</li>
					
					<li>
						<%= link_to t('menu.services'),services_path,{:class => "menu_item"} %>
					</li>
					<li>
						<%= link_to t('menu.about'),about_path,{:class  =>  "menu_item"} %>
					</li>
					<li id="site_search" style="margin-left:20px;">
						<!--searcher-->
						<input type="text" name="q" id="search_q" size="10"/>
					</li>
					<!--
					<li id="service_call">
						
							4008-123-456
					</li>
					-->
				</ul>
			</div>
			
		</div>

app/views/shared/_tm_list.html.erb
<div class="detail" id="tm_list">
	<div>
		
	<% if @category %>
	<div id="category_description">
		<%= @category.memo %>
	</div>
	<% end %>
	
	<% if !@trademarks.blank? %>
		<ul sytle="display:block;">
	  <% for tm in @trademarks %>
			<li>
				<%= link_to image_tag(tm.avatar.url(:thumb)), [tm.category,tm] %>
				<h3><%=link_to tm.name,[tm.category,tm] %></h3>
			</li>
			
	  <% end %>
		</ul>
		<div class="pagenav">
			123	
		</div>
	<% else %>
	  <div class="empty">
	  	<%= t('category.empty') %>
	  </div>
	<% end %>
	</div>
	
</div>