config/routes.rb
FamoustmRails::Application.routes.draw do |map|
  

  resources :services do
    resources :posts
  end

  
  root :to => "home#index"
  
  devise_for :users
  resources :users

  match 'trademarks/last_updated'  => 'trademarks#last_updated', :as => :trademarks_last_updated
  match '/search'  => 'trademarks#search',:as => :search_trademark
  resources :trademarks,:policies
  
  match 'categories/all' => 'categories#all_categories',:as  => :all_categories
  resources :categories do
    resources :trademarks
  end
  
  match 'about'  => "home#about" , :as  => :about
  match 'contact' => "home#contact", :as  => :contact
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :trademarks
  
  def self.all_categories
    @categories = Category.order("id").includes(:trademarks)
  end
  
  def self.find_category(id)
    Category.find(id)
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  #before_filter :authenticate_user! , :except => [:index,:show,:all_categories]
  before_filter :get_category,:only => [:edit,:update,:destroy,:show,:index,:all_categories]
  
  window_title "Category"
  def index
    
    @trademarks = Trademark.all_trademarks
  end
  
  def new
    @title = "Create a new category"
    window_title = @title
    @category = Category.new
    
  end
  
  def create
    @category = Category.new(params[:category])
    if @category.save
      flash[:notice] = "Category:#{@category.name} is created successfully."
      redirect_to category_path(@category) 
    end
  end
  
  def edit
    @title = "Edit category"
    window_title = @title
    
  end
  
  def update
    if @category.update_attributes(params[:category])
      flash[:notice] = "Update Successfully."
      redirect_to category_path(@category)
    else
      flash[:alert] = "Update failed!"
      render :action => :edit
    end
  end
  
  def destroy
    if @category.destroy
      flash[:notice] = "Deleted OK."
      redirect_to categories_path
    else
      flash[:alert] = "Delete failed"
      redirect_to category_path(@category)
    end
  end
  
  def show
    window_title = @category.name
    @trademarks = @category.trademarks
  end
  
  def all_categories
    
    render :update do |page|
      
      page.replace "tm_list",:partial => "shared/category_list"
    end
  end
  
  private
    def get_category
      @categories = Category.all_categories
      @category = Category.find_category(params[:id]) if params[:id]
    end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<% form_for @category do |f| -%>
  <%= f.label :name, "Category Name" %><br/>
  <%= f.text_field :name %>
	<p/>
  <%= f.label :memo, "Note" %><br/>
  <%= f.text_area :memo,{:size => "50x8"} %>
	<p/>
  <%= f.submit button_name %>
<% end -%>

app/views/categories/edit.html.erb
<% title @title %>

<%= error_messages_for :category %>

<%= render :partial => 'form' ,:locals => {:button_name => "Finish edit"}%>

app/views/categories/index.html.erb
<!--browse trademarks by category-->
	<% title t "category.browse_by_category" %>


	<% content_for :submenu do %>
		<!--category list-->
		<%= render :partial => 'shared/categories' %>

	<% end %>

<!--trademark list-->
<%= render :partial => 'shared/tm_list' %>

app/views/categories/new.html.erb
<% title t("category.add") %>


<%= error_messages_for :category %>

<%= render :partial => 'form',:locals => {:button_name => "Create"} %>

app/views/categories/show.html.erb
<% title @category.name %>

<% content_for :submenu do %>
	<!--category list-->
	<%= render :partial => 'shared/categories' %>

<% end %>

<%# if user_signed_in? %>
<div id="admin_category" style="display:block; margin:10px;">
	[<%= link_to t('category.edit'), edit_category_path(@category) %>][<%= link_to t('category.delete'), category_path(@category), :method => :delete,:confirm => "This will also delete all the trademarks under the category:#{@category.name}! Are you sure?" %>]
</div>
<%# end %>



<!--trademark list-->
<%= render :partial => 'shared/tm_list' %>